databases:
  - name: dokushosengen-test-db
    databaseName: dokushosengen_test_db
    user: dokushosengen-test
    region: singapore

services:
  - type: web
    name: dokushosengen-test
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dokushosengen-test-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

